### ISSUE TITLE
SideStore warning: "outdated server"

### ISSUE THREAD

**Issue by ConanArther** [Dadoum/Provision#75]
Hi again!  

SideStore keeps complaining about the custom Anisette server I deployed on my own using this repo is outdated, and that this may cause issues down the road.  
Is there a newer built I should be using, or should I just ignore the warning?

I noticed that in SideStore v0.4.0 changelog, it states that it's using Anisette V3, but the latest version in this repo is below that... Not sure if this is related or not.

Thank you.

**Comment by Dadoum** [comment]
Hey!

SideStore team is recommending to use their anisette-v3 server. For the user, anisette-v3 works as if you had your own server, so you don't even need to set-up one. The main con of anisette-v3 may be its downtimes, even if it's getting better and is going to be fixed eventually. Anyway, if you are using your private anisette server, you should be fine, it is outdated in the sense that it isn't required anymore to have a lock-less SideStore experience.

(In detail: Anisette-V3 is the name of the new protocol to contact Apple servers, instead of a single server making the calls, gathering data and distributing it to everyone, the server is now just going to do the weird Apple computations stuff, and your device will be the one making the request and part of the computations, and V3 has no link whatsoever with the Provision's version (There was an Anisette-V2 protocol for SideStore before, and Provision's anisette-server never supported it)).

**Comment by ConanArther** [comment]
So, if I'm understanding this correctly, it's actually safer to use the SideStore's v3 instead of the one I deployed, right? In terms of account locks and reliability.

**Comment by Dadoum** [comment]
It should, at least according to some other people in the SideStore team. I never got any lock from either methods so I can't really tell, both are extremely safe for sure. And if something is happening, that's supposedly due to Render's data center being suspect to Apple.
