### ISSUE TITLE
Segmentation Fault Raspberry PI Model 2 B

### ISSUE THREAD

**Issue by S1mple133** [Dadoum/Provision#84]
Hi! I downloaded the armv7 version of anisette server and when I run it on my Raspberry PI 2 Model B I get the following error

`ubuntu@ubuntu:~/altserver/anisette$ ./anisette-server-armv7 -n 127.0.0.1 -p 6969
                     app INFO  2023-07-09T10:02:02.314 anisette-server-provision v2.1.0
Segmentation fault (core dumped)`

**Comment by pinkeggy** [comment]
Hi I have the same problem. @S1mple133 do you have any solution for this? I'm also not able to build anisette-server on my raspberry pi 2 model B with ubuntu running on it.

If I run the following command:
`git clone https://github.com/Dadoum/Provision --recursive && cd Provision && mkdir build && cd build && cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release && ninja`

I'm getting the following error:
`-- The D compiler identification is unknown
CMake Error at CMakeLists.txt:4 (project):
  No CMAKE_D_COMPILER could be found.
  Tell CMake where to find the compiler by setting either the environment
  variable "DC" or the CMake cache entry CMAKE_D_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.
-- Configuring incomplete, errors occurred!`

Can someone help me?

**Comment by S1mple133** [comment]
Unfortunately, I could not find any solution yet. I also thought about building the executable myself.

You need the D Compiler for Make. I downloaded the compiler, but I get some dependency exceptions when I try to build the image. I guess the anisette server was not designed for Raspberry Pi 2, I've also tried downloading older versions, but I still got the same exception.

If you still want to try it, you can fix that exception by downloading the D Compiler (`sudo apt install gdc-arm-linux-gnueabihf`

**Comment by pinkeggy** [comment]
thank you for your answer. your command doesn't worked for me. For me this command worked:
`sudo apt-get install -y gdc`

but then i got this error:
`ninja: build stopped: subcommand failed.
CMake Error at /usr/share/cmake-3.24/Modules/FetchContent.cmake:1604 (message):
  Build step for slf4d_proj failed: 1
Call Stack (most recent call first):
  /usr/share/cmake-3.24/Modules/FetchContent.cmake:1744:EVAL:2 (__FetchContent_directPopulate)
  /usr/share/cmake-3.24/Modules/FetchContent.cmake:1744 (cmake_language)
  /usr/share/cmake-3.24/Modules/FetchContent.cmake:1958 (FetchContent_Populate)
  cmake/cmake-d/cmake-d/UseDub.cmake:103 (FetchContent_MakeAvailable)
  cmake/dependencies.cmake:6 (DubProject_Add)
  CMakeLists.txt:10 (include)
-- Configuring incomplete, errors occurred!`

**Comment by Dadoum** [comment]
You did not clone the repository recursively with submodules.

**Comment by pinkeggy** [comment]
@Dadoum thank you very much for your help. I used the following command now:
`git clone https://github.com/Dadoum/Provision --recurse-submodules && cd Provision && mkdir build && cd build && cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release && ninja`

And then i got this warning:
`CMake Warning (dev) at /usr/share/cmake-3.24/Modules/FetchContent.cmake:1267 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  cmake/cmake-d/cmake-d/UseDub.cmake:97 (FetchContent_Declare)
  cmake/dependencies.cmake:6 (DubProject_Add)
  CMakeLists.txt:10 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.`

And this error:
`FAILED: slf4d_proj-populate-prefix/src/slf4d_proj-populate-stamp/slf4d_proj-populate-patch /home/pi/Provision/build/_deps/slf4d_proj-subbuild/slf4d_proj-populate-prefix/src/slf4d_proj-populate-stamp/slf4d_proj-populate-patch
cd /home/pi/Provision/build/_deps/slf4d_proj-src && /home/pi/Provision/build/UseDub/CMakeTmp/DubToCMake -s slf4d -p slf4d && /usr/bin/cmake -E touch /home/pi/Provision/build/_deps/slf4d_proj-subbuild/slf4d_proj-populate-prefix/src/slf4d_proj-populate-stamp/slf4d_proj-populate-patch
ninja: build stopped: subcommand failed.
CMake Error at /usr/share/cmake-3.24/Modules/FetchContent.cmake:1604 (message):
  Build step for slf4d_proj failed: 1
Call Stack (most recent call first):
  /usr/share/cmake-3.24/Modules/FetchContent.cmake:1744:EVAL:2 (__FetchContent_directPopulate)
  /usr/share/cmake-3.24/Modules/FetchContent.cmake:1744 (cmake_language)
  /usr/share/cmake-3.24/Modules/FetchContent.cmake:1958 (FetchContent_Populate)
  cmake/cmake-d/cmake-d/UseDub.cmake:103 (FetchContent_MakeAvailable)
  cmake/dependencies.cmake:6 (DubProject_Add)
  CMakeLists.txt:10 (include)
-- Configuring incomplete, errors occurred!`

I think it is the same error like before. Do you have any idea what's the problem? Thank you very much for your help :)

**Comment by Dadoum** [comment]
Hav trou tried the latest build available in GitHub Actions?

**Comment by pinkeggy** [comment]
@Dadoum thank you sooooo much this was the solution. with the latest version in github Actions it worked. @S1mple133 I hope this works for you too.

**Comment by S1mple133** [comment]
Oh, I've downloaded the executable from releases. Should do it, thanks !
