### ISSUE TITLE
Provision doesn't work on Apple Silicon macs (bus error)

### ISSUE THREAD

**Issue by dd-dreams** [Dadoum/Provision#97]
I'm running the build from Actions for macOS arm64.
The following error happens:
```
$ ./anisette-server-macos-arm64
...
...
app INFO Machine requires provisioning...
bus error: ./anisette-server-macos-arm64
```
After some debugging, it appears it happens at `adi.d:207`, where the reason it crashes is: `EXC_BAD_ACCESS`.

Any idea what could this be?

**Comment by Dadoum** [comment]
Provision doesn't currently works on macOS arm64, and that's related to the fact that the Apple libraries for Android are made for device with a page size of 4 kB, while their Apple Silicon chips have a page size of 16 kB (pages allow the CPU to know if the memory is intended to contain code to execute or memory to read and write from). I tried something by shifting pages a bit and changing perms but in its current state it still doesn't work, sorry.

**Comment by dd-dreams** [comment]
Does the Apple libraries for Android need to be used necessarily? This is also useful for macOS apps.

**Comment by Dadoum** [comment]
No they should not be needed but I got no mac to try to find another framework for that currently unfortunately.

I could use AOSKit (which is the framework used by apps like AltServer and SideServer) but it will give the anisette data from the current system, while I like the idea that Provision maintains its own fake computer.

(Also, the programming language I use should have Objective-C interoperability (the language used in macOS system frameworks), however it doesn't currently work on arm64 unfortunately so it's a bit more annoying, but that's okay still.)

I think some frameworks might give a way to make custom anisette data from the ground up but I just got no computer to test that currently. Sorry.

I leave the issue open though since it's still a real issue.

**Comment by dd-dreams** [comment]
I guess I'll start working on that myself. Thanks.

**Comment by Dadoum** [comment]
I think I fixed it @dd-dreams

**Comment by dd-dreams** [comment]
Yep. Not crashing. Thanks!
